import type { Metadata } from "next";
import { Chicle, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Chicle({
  variable: "--font-chicle",
  subsets: ["latin"],
  weight: '400'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable}`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
